INSERT INTO `departaments` (`id`, `name`, `iso`, `countries_id`, `created_at`) VALUES
(5, 'Antioquia', 'ANT', 1, NOW()),
(8, 'Atlántico', 'ATL', 1, NOW()),
(11, 'Bogotá', 'DC', 1, NOW()),
(13, 'Bolívar', 'BOL', 1, NOW()),
(15, 'Boyacá', 'BOY', 1, NOW()),
(17, 'Caldas', 'CAL', 1, NOW()),
(18, 'Caquetá', 'CAQ', 1, NOW()),
(19, 'Cauca', 'CAU', 1, NOW()),
(20, 'Cesar', 'CES', 1, NOW()),
(23, 'Córdoba', 'COR', 1, NOW()),
(25, 'Cundinamarca', 'CUN', 1, NOW()),
(27, 'Chocó', 'CHO', 1, NOW()),
(41, 'Huila', 'HUI', 1, NOW()),
(44, 'La Guajira', 'LAG', 1, NOW()),
(47, 'Magdalena', 'MAG', 1, NOW()),
(50, 'Meta', 'MET', 1, NOW()),
(52, 'Nariño', 'NAR', 1, NOW()),
(54, 'Norte de Santander', 'NSA', 1, NOW()),
(63, 'Quindío', 'QUI', 1, NOW()),
(66, 'Risaralda', 'RIS', 1, NOW()),
(68, 'Santander', 'SAN', 1, NOW()),
(70, 'Sucre', 'SUC', 1, NOW()),
(73, 'Tolima', 'TOL', 1, NOW()),
(76, 'Valle del Cauca', 'VAC', 1, NOW()),
(81, 'Arauca', 'ARA', 1, NOW()),
(85, 'Casanare', 'CAS', 1, NOW()),
(86, 'Putumayo', 'PUT', 1, NOW()),
(88, 'San Andrés y Providencia', 'SAP', 1, NOW()),
(91, 'Amazonas', 'AMA', 1, NOW()),
(94, 'Guainía', 'GUA', 1, NOW()),
(95, 'Guaviare', 'GUV', 1, NOW()),
(97, 'Vaupés', 'VAU', 1, NOW()),
(99, 'Vichada', 'VID', 1, NOW()),
(100, 'Otros', 'NA', 2, NOW());

