INSERT INTO `payment_methods` (`id`, `name`, `created_at`) VALUES
('1', 'Instrumento no definido', NOW()),
('2', 'Crédito ACH', NOW()),
('3', 'Débito ACH', NOW()),
('4', 'Reversión débito de demanda ACH', NOW()),
('5', 'Reversión crédito de demanda ACH', NOW()),
('6', 'Crédito de demanda ACH', NOW()),
('7', 'Débito de demanda ACH', NOW()),
('8', 'Mantener', NOW()),
('9', 'Clearing Nacional o Regional', NOW()),
('10', 'Efectivo', NOW()),
('11', 'Reversión Crédito Ahorro', NOW()),
('12', 'Reversión Débito Ahorro', NOW()),
('13', 'Crédito Ahorro', NOW()),
('14', 'Débito Ahorro', NOW()),
('15', 'Bookentry Crédito', NOW()),
('16', 'Bookentry Débito', NOW()),
('17', 'Concentración de la demanda en efectivo/Desembolso Crédito (CCD)', NOW()),
('18', 'Concentración de la demanda en efectivo /Desembolso (CCD) débito', NOW()),
('19', 'Crédito Pago negocio corporativo (CTP)', NOW()),
('20', 'Cheque', NOW()),
('21', 'Poyecto bancario', NOW()),
('22', 'Proyecto bancario certificado', NOW()),
('23', 'Cheque bancario', NOW()),
('24', 'Nota cambiaria esperando aceptación', NOW()),
('25', 'Cheque certificado', NOW()),
('26', 'Cheque Local', NOW()),
('27', 'Débito Pago Neogcio Corporativo (CTP)', NOW()),
('28', 'Crédito Negocio Intercambio Corporativo (CTX)', NOW()),
('29', 'Débito Negocio Intercambio Corporativo (CTX)', NOW()),
('30', 'Transferecia Crédito', NOW()),
('31', 'Transferencia Débito', NOW()),
('32', 'Concentración Efectivo / Desembolso Crédito plus (CCD+)', NOW()),
('33', 'Concentración Efectivo / Desembolso Débito plus (CCD+)', NOW()),
('34', 'Pago y depósito pre acordado (PPD)', NOW()),
('35', 'Concentración efectivo ahorros / Desembolso Crédito (CCD)', NOW()),
('36', 'Concentración efectivo ahorros / Desembolso Drédito (CCD)', NOW()),
('37', 'Pago Negocio Corporativo Ahorros Crédito (CTP)', NOW()),
('38', 'Pago Neogcio Corporativo Ahorros Débito (CTP)', NOW()),
('39', 'Crédito Negocio Intercambio Corporativo (CTX)', NOW()),
('40', 'Débito Negocio Intercambio Corporativo (CTX)', NOW()),
('41', 'Concentración efectivo/Desembolso Crédito plus (CCD+)', NOW()),
('42', 'Consiganción bancaria', NOW()),
('43', 'Concentración efectivo / Desembolso Débito plus (CCD+)', NOW()),
('44', 'Nota cambiaria', NOW()),
('45', 'Transferencia Crédito Bancario', NOW()),
('46', 'Transferencia Débito Interbancario', NOW()),
('47', 'Transferencia Débito Bancaria', NOW()),
('48', 'Tarjeta Crédito', NOW()),
('49', 'Tarjeta Débito', NOW()),
('50', 'Postgiro', NOW()),
('51', 'Telex estándar bancario francés', NOW()),
('52', 'Pago comercial urgente', NOW()),
('53', 'Pago Tesorería Urgente', NOW()),
('60', 'Nota promisoria', NOW()),
('61', 'Nota promisoria firmada por el acreedor', NOW()),
('62', 'Nota promisoria firmada por el acreedor, avalada por el banco', NOW()),
('63', 'Nota promisoria firmada por el acreedor, avalada por un tercero', NOW()),
('64', 'Nota promisoria firmada pro el banco', NOW()),
('65', 'Nota promisoria firmada por un banco avalada por otro banco', NOW()),
('66', 'Nota promisoria firmada', NOW()),
('67', 'Nota promisoria firmada por un tercero avalada por un banco', NOW()),
('70', 'Retiro de nota por el por el acreedor', NOW()),
('71', 'Bonos', NOW()),
('72', 'Vales', NOW()),
('74', 'Retiro de nota por el por el acreedor sobre un banco', NOW()),
('75', 'Retiro de nota por el acreedor, avalada por otro banco', NOW()),
('76', 'Retiro de nota por el acreedor, sobre un banco avalada por un tercero', NOW()),
('77', 'Retiro de una nota por el acreedor sobre un tercero', NOW()),
('78', 'Retiro de una nota por el acreedor sobre un tercero avalada por un banco', NOW()),
('91', 'Nota bancaria tranferible', NOW()),
('92', 'Cheque local traferible', NOW()),
('93', 'Giro referenciado', NOW()),
('94', 'Giro urgente', NOW()),
('95', 'Giro formato abierto', NOW()),
('96', 'Método de pago solicitado no usuado', NOW()),
('97', 'Clearing entre partners', NOW()),
('ZZZ', 'Acuerdo mutuo', NOW());
